language: c

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt562
  - sudo apt-get update
  - sudo apt-get install qt56-meta

install:
  - make arm_sdk_install

env:
  - FLIGHT_BUILD_CONF=release

script:
  - make -j2 all_flight
