language: c++
dist: trusty
sudo: false

cache:
  - ccache
  - directories:
    - downloads
before_cache:
  - find downloads -type f -not -name 'gcc-arm-none-eabi-*.bz2' -print0 | xargs -0 rm --

# need to be able to see back to upstream/next for version-info.py ancestor
git:
  depth: 100

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # tools
    - g++-5
    - gcc-5
    # deps
    - gcc-multilib
    - zlib1g-dev
    - libusb-1.0-0-dev
    - libudev-dev
    - libgl1-mesa-dev

before_install:
# sneaky hax to use gcc-5 without sudo
  - mkdir -p ~/bin
  - ln -fs /usr/bin/gcc-5 ~/bin/gcc
  - ln -fs /usr/bin/g++-5 ~/bin/g++
  - gcc --version
  - g++ --version

install:
  - xvfb-run make qt_sdk_install | grep -Ev "(^\[[0-9]*\] Warning:|^[0-9\. \t]*[KMG])"
  - make arm_sdk_install

before-script:
  - ccache -z
# remove this before checking into main repo
  - git remote add upstream https://github.com/d-ronin/dronin.git

script:
  - make -j2 gcs
  - make -j2 all_flight

after-script:
  - ccache -s
