language: c++
dist: trusty
sudo: false

cache:
  - ccache
  - directories:
    - downloads
    - tools/breakpad
before_cache:
  - find downloads -type f -not -name 'gcc-arm-none-eabi-*.bz2' -print0 | xargs -0 rm --

# need to be able to see back to upstream/next for version-info.py ancestor
git:
  depth: 100

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # tools
    - g++-5
    - gcc-5
    # deps
    - gcc-5-multilib
    - gcc-multilib # needed for asm/errno.h?
    - zlib1g-dev
    - libusb-1.0-0-dev
    - libudev-dev
    - libgl1-mesa-dev
    - libpulse0
    - libpulse-mainloop-glib0
    - libpulse-dev

before_install:
# sneaky hax to use gcc-5 without sudo
  - mkdir -p ~/bin
  - ln -fs /usr/bin/gcc-5 ~/bin/gcc
  - ln -fs /usr/bin/g++-5 ~/bin/g++
  - gcc --version
  - g++ --version

install:
  - xvfb-run make qt_sdk_install | grep -Ev "(^\[[0-9]*\] Warning:|^[0-9\. \t]*[KMG])"
  - make arm_sdk_install
  - make tools_required_breakpad || make breakpad_install

before_script:
  - ccache -z
# remove this before checking into main repo, will still fetch to fetch next branch though
  - git remote add upstream https://github.com/d-ronin/dronin.git && git fetch -q --depth=100 upstream next
  - git merge-base upstream/next HEAD

script:
  - make -j4 gcs 2> >(tee gcserr.log >&2)
  - make -j4 all_flight 2> >(tee flighterr.log >&2)

after_script:
  - ccache -s
  - echo "\nGCS Build Errors:\n" && cat gcserr.log
  - echo "\nFlight Build Errors:\n" && cat flighterr.log
