language: c

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt562
  - sudo apt-get -y -q update
  - sudo apt-get -y -q install qt56-meta

install:
  - make arm_sdk_install

env:
  - FLIGHT_BUILD_CONF=release

script:
  - make -j2 all_flight
