#!/usr/bin/env bash -e -v

APP="${1?}"
PLUGINS="${APP}/Contents/Plugins"

# Specify a list of all the qml directories that need imports
QMLDIR="${APP}/Contents/Resources/welcome"

# macdeployqt will copy all the Qt5 binaries to the app bundle and relink as appropriate

#pushd/popd: workaround QTBUG-46404 -- need to be next to macdeployqt's path

pushd "${QT_SDK_BIN_PATH}"

./macdeployqt "${APP}" -verbose=2 -no-strip -always-overwrite -qmldir="$QMLDIR" -executable="${APP}/Contents/MacOS/crashreporterapp"

# hack to workaround QTBUG-57265 (macdeployqt copies debug symbols from dSYM bundle instead of real dylib)
mkdir -p "${APP}/Contents/Plugins/quick/"
cp -f "${QT_SDK_BIN_PATH}/../qml/QtQuick.2/libqtquick2plugin.dylib" "${APP}/Contents/Plugins/quick/"
cp -f "${QT_SDK_BIN_PATH}/../qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.dylib" "${APP}/Contents/Plugins/quick/"

popd

# For some reasom this symlink is still wrong..
CWD=`pwd`
cd "${APP}/Contents/Resources/qml/QtQuick/XmlListModel/"
rm libqmlxmllistmodelplugin.dylib
ln -s ../../../../Plugins/quick/libqmlxmllistmodelplugin.dylib
cd ${CWD}

