# dRonin build environment setup
# we only inject our stuff into the env. if the shell is started inside the dronin tree
# if you want to activate dronin env outside the tree, try 'source "${DRONIN_ROOT}/make/winx86/win_env.sh" "${DRONIN_ROOT}"'
# where ${DRONIN_ROOT} is the root of the dRonin tree
DRONIN_ROOT=""
CURRDIR=`readlink -f ${PWD}`
while [ `echo "${CURRDIR}" | grep -o / | wc -l` -gt 1 ]; do
  if [ -f "${CURRDIR}/.dronin_root" ]; then
    DRONIN_ROOT=$CURRDIR
    break
  fi
  CURRDIR=`readlink -f "${CURRDIR}/.."`
done

if [ -n "${DRONIN_ROOT}" ]; then
  echo "Setting up dRonin build environment for ${DRONIN_ROOT}"
  source "${DRONIN_ROOT}/make/winx86/win_env.sh" "${DRONIN_ROOT}"
fi
